config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, skip: :registrations
  devise_for :admins, skip: :registrations

  resources :users

  resources :messages

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :password, presence: {message: "can't be blank"}
  validates :password, length: { minimum: 7 }
end

app/models/message.rb
class Message < ActiveRecord::Base

  validates :body, presence: true

  scope :unread_for, ->(user_id) {where(recipient_id: user_id, read: false)}
  scope :latest_messages, ->(user_id) {where(['sender_id = ? or recipient_id = ?', user_id, user_id]).order('created_at DESC')}
  scope :load_conversation, ->(user1_id, user2_id) { where(['recipient_id = ? AND sender_id = ? OR recipient_id = ? AND sender_id = ?', user1_id, user2_id, user2_id, user1_id]).order('created_at DESC')}

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :default_password

  scope :all_except, ->(user) { where.not(id: user) }
  scope :not_banned, -> { where(banned: false) }

  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id
  has_many :received_messages, class_name: 'Message', foreign_key: :receiver_id

  validates :name, presence: true, format: /\A[a-zA-Z\s\'-]+\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      sign_out(:user)
      users_path
    else
      sign_out(:admin)
      messages_path
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.unread_for(current_user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(messenger_params)
    if @message.save
      redirect_to message_path(@message.recipient_id)
    else
      render :show
    end
  end

  def show
    @message = Message.new
    @messages = Message.load_conversation(current_user.id, params[:id].to_i)

    set_messages_as_read if params[:read] == 'true'
  end

  private

  def set_messages_as_read
    Message.unread_for(current_user).update_all(read: true)
  end

  def messenger_params
    params.require(:message).permit(:body, :recipient_id).merge!(sender_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  DEFAULT_PASSWORD = 'simple_the_best'

  before_filter :authenticate_any_to_update!, only: [:edit, :update]
  before_filter :authenticate_admin!, except: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    set_default_password(@user) if params[:user][:default_password] == 'true'

    if @user.save
      redirect_to users_path, notice: 'user was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to after_update
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'user was successfully destroyed.'
  end

  private

  def after_update
    admin_signed_in? ? users_path : message_path
  end

  def authenticate_any_to_update!
    if admin_signed_in?
      true
    else
      authenticate_user!
    end
  end

  def set_default_password(user)
    user.password = DEFAULT_PASSWORD
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :default_password, :banned)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @unread_message_count = Message.unread_for(current_user).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation_login.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar.collapse.navbar-collapse
      - if user_signed_in? || admin_signed_in?
        - if user_signed_in?
          %ul.nav.navbar-nav
            %li
              = link_to 'Edit profile',  edit_user_path(current_user)
            %li
              = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav
            %li
              = link_to 'Log out', destroy_admin_session_path, method: :delete
      - else
        %ul.nav.navbar-nav
          %li
            = link_to 'Log in as user', new_user_session_path
          %li
            = link_to 'Log in as admin', new_admin_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Starter Template for Bootstrap

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation_login'
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/messages/_list_of_messages.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th sender
        %th body
        %th time ago
        %th answer to message
    %tbody
      - @messages.each do |message|
        %tr
          %td= message.sender.name
          %td= message.body
          %td= time_ago_in_words(message.created_at)
          %td= link_to 'Answer to message', message_path(message.sender, read: true)
%br
  = link_to 'Update List', '', class: 'btn btn-primary', id: 'update_unread_count'

:javascript
  $(function() {
    $(document).ready(function() {
      setInterval(function() {
        $.ajax({
          url: "/messages",
          type: "GET",
          dataType: "script"
        });
      }, 600000);
    });
  });

app/views/messages/index.html.haml
%h1 Unread Messages
#messages-list
  = render 'list_of_messages'
%br
= link_to 'Write New Message', new_message_path

app/views/messages/index.js.erb
$("#messages-list").html("<%= escape_javascript(render(:partial => 'list_of_messages')) %>");

app/views/messages/new.html.haml
= form_for @message, html: { class: "form-horizontal", role: "form" } do |f|
  -if @message.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"

      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :body, class: 'form-control'
  .form-group
    = f.label 'Select User', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :recipient_id, User.all_except(current_user).not_banned.collect {|p| [ p.name, p.id ] }, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/messages/show.html.haml
= form_for @message, html: { class: "form-horizontal", role: "form" } do |f|
  = hidden_field_tag('message[recipient_id]', params[:id])
  -if @message.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"

      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :body, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

- if @messages.presence
  - @messages.each do |message|
    = "#{message.sender.name} ->  #{message.body}"
    %sub= time_ago_in_words(message.created_at)
    %br

app/views/users/_form_for_admin.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, 'error')
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |user|
          %li= user
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label 'Set default password'
    = f.check_box :default_password, {id: 'default_pass_check_box'}, true, false
  .field.user-password-field
    = f.label :password
    = f.password_field :password
  .field
    = f.label 'Ban'
    = f.check_box :banned
  .actions
    = f.submit 'Save'

app/views/users/_form_for_user.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, 'error')
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |user|
          %li= user
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.email_field :email
  .field.user-password-field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user
- if current_admin
  = render 'form_for_admin'
  = link_to 'Show', @user
  |
  = link_to 'Back', users_path
- else
  = render 'form_for_user'

app/views/users/index.html.haml
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th name
        %th banned?
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.banned
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New user', new_user_path

app/views/users/new.html.haml
%h1 New user
= render 'form_for_admin'
= link_to 'Back', users_path

app/views/users/show.html.haml
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path

app/views/welcome/index.html.haml
- if user_signed_in?
  - if @unread_message_count > 0
    Hi, you have
    = link_to "#{@unread_message_count} unread messages", messages_path
  - else
    You don't have new messages
  %br/
  = link_to 'Write New Message', new_message_path
- else
  Please log in